/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.9.0.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as exploreFood from "../exploreFood.js";
import type * as messages from "../messages.js";
import type * as openai from "../openai.js";
import type * as specialItems from "../specialItems.js";
import type * as userPlates from "../userPlates.js";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  exploreFood: typeof exploreFood;
  messages: typeof messages;
  openai: typeof openai;
  specialItems: typeof specialItems;
  userPlates: typeof userPlates;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
